# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joshua Thornell - CV Portfolio
email: JoshThornell94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Joshua Thornell and this is my personal website where I will be sharing my own personal achievments and accomplishments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  JoshThornell

# Build settings
markdown: kramdown
